@host=http://localhost:3000

### Test
GET {{host}}/test



# ------ USER

### Get all users
GET {{host}}/user

### Get one user
GET {{host}}/user/1

### Create new user
POST {{host}}/user
Content-Type: application/json

{
    "firstname": "Tony",
    "lastname": "Montana",
    "email": "toto@montana.ca",
    "password": "qwerty"
}

### Update user
POST {{host}}/user
Content-Type: application/json

{
    "id": 4,
    "firstname": "Maurice",
    "lastname": "Montana",
    "email": "toto@montana.ca",
    "password": "azerty"
}

### Delete one user
DELETE {{host}}/user/4



# ------ OFFER

### Get all offers
GET {{host}}/offers

### Get one offer
GET {{host}}/offers/1

### Create new offer
POST {{host}}/offers
Content-Type: application/json

{
    "title": "Ma cabane au fond du jardin",
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dapibus gravida vestibulum. Curabitur ac elit a elit mattis lobortis. Maecenas lacinia nisl ut accumsan venenatis. Vivamus at enim tempor, dapibus enim eget, ultrices elit. Aliquam efficitur eleifend odio, suscipit vestibulum ipsum.",
    "zip_code": "22546",
    "city_name": "Trifouillie-les-oies",
    "country": "France",
    "street_name": "rue des alouettes",
    "street_number": "458",
    "price_ht": 30000,
    "tax": 30,
    "main_picture": "https://images.pexels.com/photos/4558580/pexels-photo-4558580.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    "location_id": 3
}

### Update offer
POST {{host}}/offers
Content-Type: application/json

{
    "id": 3,
    "title": "Ma cabane au fond du jardin",
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dapibus gravida vestibulum. Curabitur ac elit a elit mattis lobortis. Maecenas lacinia nisl ut accumsan venenatis. Vivamus at enim tempor, dapibus enim eget, ultrices elit. Aliquam efficitur eleifend odio, suscipit vestibulum ipsum.",
    "zip_code": "22546",
    "city_name": "Trifouillie-les-oies",
    "country": "France",
    "street_name": "rue des alouettes",
    "street_number": "458",
    "latitude": "687646.64768.02",
    "longitude": "7458.4521.62",
    "price_ht": 30000,
    "tax": 30,
    "main_picture": "https://images.pexels.com/photos/4558580/pexels-photo-4558580.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    "galery_picture_1": "https://images.pexels.com/photos/745054/pexels-photo-745054.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    "galery_picture_2": "https://images.pexels.com/photos/2422464/pexels-photo-2422464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    "location_id": 3
}

### Delete one offer
DELETE {{host}}/offers/3



# ------ MESSAGE

### Get all messages
GET {{host}}/messages

### Get one messages
GET {{host}}/messages/1

### Create new message
POST {{host}}/messages
Content-Type: application/json

{
    "reservation_start": "2021-10-16 10:00:00+02",
    "reservation_end": "2021-10-23 14:00:00+02",
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dapibus gravida vestibulum. Curabitur ac elit a elit mattis lobortis. Maecenas lacinia nisl ut accumsan venenatis. Vivamus at enim tempor, dapibus enim eget, ultrices elit. Aliquam efficitur eleifend odio, suscipit vestibulum ipsum.",
    "offer_id": 2,
    "user_id": 1
}

### Update message
POST {{host}}/messages
Content-Type: application/json

{
    "id": 3,
    "reservation_start": "2021-10-16 04:00:00+02",
    "reservation_end": "2021-10-23 18:00:00+02",
    "nb_persons": 12,
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dapibus gravida vestibulum. Curabitur ac elit a elit mattis lobortis. Maecenas lacinia nisl ut accumsan venenatis. Vivamus at enim tempor, dapibus enim eget, ultrices elit. Aliquam efficitur eleifend odio, suscipit vestibulum ipsum.",
    "offer_id": 2,
    "user_id": 1
}

### Delete one message
DELETE {{host}}/messages/3



# ------ BOOKING

### Get all bookings
GET {{host}}/bookings

### Get one booking
GET {{host}}/bookings/1

### Create new booking
POST {{host}}/bookings
Content-Type: application/json

{
    "reservation_start": "2021-10-16 04:00:00+02",
    "reservation_end": "2021-10-23 18:00:00+02",
    "offer_id": 2,
    "user_id": 1
}

### Update booking
POST {{host}}/bookings
Content-Type: application/json

{
    "id": 3,
    "reservation_start": "2021-11-16 19:00:00+02",
    "reservation_end": "2021-11-23 20:00:00+02",
    "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dapibus gravida vestibulum. Curabitur ac elit a elit mattis lobortis. Maecenas lacinia nisl ut accumsan venenatis. Vivamus at enim tempor, dapibus enim eget, ultrices elit. Aliquam efficitur eleifend odio, suscipit vestibulum ipsum.",
    "reservation_status": true,
    "offer_id": 2,
    "user_id": 1
}

### Delete one booking
DELETE {{host}}/bookings/3




# ------ COMMENT

### Get all comments
GET {{host}}/comments

### Get one comment
GET {{host}}/comments/1

### Create new comment
POST {{host}}/comments
Content-Type: application/json

{
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dapibus gravida vestibulum. Curabitur ac elit a elit mattis lobortis. Maecenas lacinia nisl ut accumsan venenatis. Vivamus at enim tempor, dapibus enim eget, ultrices elit. Aliquam efficitur eleifend odio, suscipit vestibulum ipsum.",
    "note": 5,
    "offer_id": 2,
    "user_id": 1
}

### Update comment
POST {{host}}/comments
Content-Type: application/json

{
    "id": 4,
    "body": "Lorem ipsum dolor sit amet.",
    "note": 2,
    "offer_id": 2,
    "user_id": 1
}

### Delete one comment
DELETE {{host}}/comments/4
